#set the process info file
pid /run/nginx.pid;

#set the worker process amount to automatic
worker_processes  auto;

events {
    #set the max connections that the worker process can run
    worker_connections  1024;
}

http {
    #set the log format for the access log
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
    
    #set the logs path and level
    error_log  /var/log/nginx/error.log notice;
    access_log  /var/log/nginx/access.log  main;

    #include the file that's for mapping file types to file extensions for browsers
    include       /etc/nginx/mime.types;
    #fallback file types for the ones not in mime.types
    default_type  application/octet-stream;

    #improve performance of the reverse proxy
    sendfile on;
    tcp_nopush on;


    #how long should a idle connection be kept before killling it.
    keepalive_timeout  65;

    # import the sites to use
    include /etc/nginx/conf.d/*.conf;
}
