server {
    #port and domain name
    listen 80;
    server_name omv.uhhhhh;

    #log the access and error for this site
    access_log /var/log/nginx/omv-access.log;
    error_log /var/log/nginx/omv-error.log;

    location / {
        #redirect to the new server
        proxy_pass http://10.10.0.13:80;
        
        #pass the request headers for the host name and ip
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        #websocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_buffering off;

        #keep the orginal ip address
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        #keep the orginal http or https request
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}


server {
    #port and domain name
    listen 443 ssl;
    server_name omv.uhhhhh;

    #log the access and error for this site
    access_log /var/log/nginx/omv-access.log;
    error_log /var/log/nginx/omv-error.log;

    #ssl certificate keys
    ssl_certificate /etc/certs/omv.uhhhhh.crt; #public
    ssl_certificate_key /etc/certs/omv.uhhhhh.key; #private

    #ssl protocals support
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;

    #what encryption algorithms to be used
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        #redirect to the new server
        proxy_pass http://127.0.0.1:80;

        
        #pass the request headers for the host name and ip
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        #websocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_buffering off;

        #keep the orginal ip address
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        #keep the orginal http or https request
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}